/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parqueadero.presentacion;

/**
 *
 * @author braya
 */
public class Ticket extends javax.swing.JDialog {

    public Ticket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       mostrarusuario.setText(RegistrarUsuario.usuario); 
       int codigo = (int) (Math.random() * 99 + 1);
       int puesto = (int) (Math.random() * 20 + 1);
       mostrarcodigo.setText(String.valueOf("PB" + codigo));
       mostrarpuesto.setText(String.valueOf(puesto));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mostrarcodigo = new javax.swing.JTextField();
        mostrarusuario = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mostrarpuesto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TICKET ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 30, 78, 21);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 70, 60, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 100, 60, 30);

        mostrarcodigo.setEditable(false);
        mostrarcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarcodigoActionPerformed(evt);
            }
        });
        jPanel2.add(mostrarcodigo);
        mostrarcodigo.setBounds(120, 100, 200, 30);

        mostrarusuario.setEditable(false);
        mostrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(mostrarusuario);
        mostrarusuario.setBounds(120, 70, 200, 32);

        aceptar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(aceptar);
        aceptar.setBounds(230, 180, 90, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Puesto");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 130, 60, 30);

        mostrarpuesto.setEditable(false);
        jPanel2.add(mostrarpuesto);
        mostrarpuesto.setBounds(120, 130, 200, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 390, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 230);

        setSize(new java.awt.Dimension(408, 269));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
       this.dispose();
    }//GEN-LAST:event_aceptarActionPerformed

    private void mostrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarusuarioActionPerformed
 
    }//GEN-LAST:event_mostrarusuarioActionPerformed

    private void mostrarcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarcodigoActionPerformed
       
    }//GEN-LAST:event_mostrarcodigoActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ticket dialog = new Ticket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mostrarcodigo;
    private javax.swing.JTextField mostrarpuesto;
    private javax.swing.JTextField mostrarusuario;
    // End of variables declaration//GEN-END:variables
}
